/*
 * Babiling
 * Copyright (C) 2016  Neil Roberts
 *
 * Permission to use, copy, modify, distribute, and sell this software and its
 * documentation for any purpose is hereby granted without fee, provided that
 * the above copyright notice appear in all copies and that both that copyright
 * notice and this permission notice appear in supporting documentation, and
 * that the name of the copyright holders not be used in advertising or
 * publicity pertaining to distribution of the software without specific,
 * written prior permission.  The copyright holders make no representations
 * about the suitability of this software for any purpose.  It is provided "as
 * is" without express or implied warranty.
 *
 * THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
 * INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
 * EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY SPECIAL, INDIRECT OR
 * CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
 * DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
 * TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE
 * OF THIS SOFTWARE.
 */

#ifndef FV_FLAG_H
#define FV_FLAG_H

/* The flag number is a uint32_t. The value is derived from one of the
 * following:
 *
 * For flags that represent a country the number will be the 3-digit
 * ISO 3166 number multiplied by 65536.
 *
 * Flags representing a subdivision within a country use the same
 * format as above bitwise OR'd with a value based on the subdivision
 * code. The value is calculated by by multiplying the first letter by
 * 27², the second letter by 27 and adding the third letter, where A=1
 * and Z=26. Codes with fewer letters use zero as the missing letter
 * values.
 *
 * For flags that represent a language directly, the value is 2³⁰
 * bitwise OR'd with a value based on the three-digit language code
 * from ISO-639-2, combined as above for the subdivision code.
 */

#define LETTER_VALUE(letter) \
        ((letter) == 0 ? 0 : \
         (letter) >= 'a' ? (letter) - 'a' + 1 : \
         (letter) - 'A' + 1)
#define THREE_LETTER_CODE(letter_a, letter_b, letter_c) \
        (LETTER_VALUE(letter_a) * 27 * 27 +             \
         LETTER_VALUE(letter_b) * 27 +                  \
         LETTER_VALUE(letter_c))

#define MAKE_COUNTRY(name, iso_number) \
        FV_FLAG_ ## name = iso_number * 65536
#define MAKE_SUBDIVISION(name, country, letter_a, letter_b, letter_c)   \
        FV_FLAG_ ## name = (FV_FLAG_ ## country) | \
                THREE_LETTER_CODE(letter_a, letter_b, letter_c)
#define MAKE_LANGUAGE(name, letter_a, letter_b, letter_c) \
        FV_FLAG_ ## name = (1 << 30) | \
                THREE_LETTER_CODE(letter_a, letter_b, letter_c)

enum fv_flag {
        MAKE_COUNTRY(AFGHANISTAN, 4),
        MAKE_COUNTRY(ALBANIA, 8),
        MAKE_COUNTRY(ANTARCTICA, 10),
        MAKE_COUNTRY(ALGERIA, 12),
        MAKE_COUNTRY(AMERICAN_SAMOA, 16),
        MAKE_COUNTRY(ANDORRA, 20),
        MAKE_COUNTRY(ANGOLA, 24),
        MAKE_COUNTRY(ANTIGUA_AND_BARBUDA, 28),
        MAKE_COUNTRY(AZERBAIJAN, 31),
        MAKE_COUNTRY(ARGENTINA, 32),
        MAKE_COUNTRY(AUSTRALIA, 36),
        MAKE_COUNTRY(AUSTRIA, 40),
        MAKE_COUNTRY(BAHAMAS, 44),
        MAKE_COUNTRY(BAHRAIN, 48),
        MAKE_COUNTRY(BANGLADESH, 50),
        MAKE_COUNTRY(ARMENIA, 51),
        MAKE_COUNTRY(BARBADOS, 52),
        MAKE_COUNTRY(BELGIUM, 56),
        MAKE_COUNTRY(BERMUDA, 60),
        MAKE_COUNTRY(BHUTAN, 64),
        MAKE_COUNTRY(BOLIVIA, 68),
        MAKE_COUNTRY(BOSNIA_AND_HERZEGOVINA, 70),
        MAKE_COUNTRY(BOTSWANA, 72),
        MAKE_COUNTRY(BRAZIL, 76),
        MAKE_COUNTRY(BELIZE, 84),
        MAKE_COUNTRY(BRITISH_INDIAN_OCEAN_TERRITORY, 86),
        MAKE_COUNTRY(SOLOMON_ISLANDS, 90),
        MAKE_COUNTRY(BRITISH_VIRGIN_ISLANDS, 92),
        MAKE_COUNTRY(BRUNEI_DARUSSALAM, 96),
        MAKE_COUNTRY(BULGARIA, 100),
        MAKE_COUNTRY(MYANMAR, 104),
        MAKE_COUNTRY(BURUNDI, 108),
        MAKE_COUNTRY(BELARUS, 112),
        MAKE_COUNTRY(CAMBODIA, 116),
        MAKE_COUNTRY(CAMEROON, 120),
        MAKE_COUNTRY(CANADA, 124),
        MAKE_COUNTRY(CABO_VERDE, 132),
        MAKE_COUNTRY(CAYMAN_ISLANDS, 136),
        MAKE_COUNTRY(CENTRAL_AFRICAN_REPUBLIC, 140),
        MAKE_COUNTRY(SRI_LANKA, 144),
        MAKE_COUNTRY(CHAD, 148),
        MAKE_COUNTRY(CHILE, 152),
        MAKE_COUNTRY(CHINA, 156),
        MAKE_COUNTRY(TAIWAN_PROVINCE_OF_CHINA, 158),
        MAKE_COUNTRY(CHRISTMAS_ISLAND, 162),
        MAKE_COUNTRY(COCOS_KEELING_ISLANDS, 166),
        MAKE_COUNTRY(COLOMBIA, 170),
        MAKE_COUNTRY(COMOROS, 174),
        MAKE_COUNTRY(CONGO, 178),
        MAKE_COUNTRY(THE_DEMOCRATIC_REPUBLIC_OF_THE_CONGO, 180),
        MAKE_COUNTRY(COOK_ISLANDS, 184),
        MAKE_COUNTRY(COSTA_RICA, 188),
        MAKE_COUNTRY(CROATIA, 191),
        MAKE_COUNTRY(CUBA, 192),
        MAKE_COUNTRY(CYPRUS, 196),
        MAKE_COUNTRY(CZECH_REPUBLIC, 203),
        MAKE_COUNTRY(BENIN, 204),
        MAKE_COUNTRY(DENMARK, 208),
        MAKE_COUNTRY(DOMINICA, 212),
        MAKE_COUNTRY(DOMINICAN_REPUBLIC, 214),
        MAKE_COUNTRY(ECUADOR, 218),
        MAKE_COUNTRY(EL_SALVADOR, 222),
        MAKE_COUNTRY(EQUATORIAL_GUINEA, 226),
        MAKE_COUNTRY(ETHIOPIA, 231),
        MAKE_COUNTRY(ERITREA, 232),
        MAKE_COUNTRY(ESTONIA, 233),
        MAKE_COUNTRY(FAROE_ISLANDS, 234),
        MAKE_COUNTRY(FALKLAND_ISLANDS_MALVINAS, 238),
        MAKE_COUNTRY(SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS, 239),
        MAKE_COUNTRY(FIJI, 242),
        MAKE_COUNTRY(FINLAND, 246),
        MAKE_COUNTRY(ALAND_ISLANDS, 248),
        MAKE_COUNTRY(FRANCE, 250),
        MAKE_COUNTRY(FRENCH_GUIANA, 254),
        MAKE_COUNTRY(FRENCH_POLYNESIA, 258),
        MAKE_COUNTRY(DJIBOUTI, 262),
        MAKE_COUNTRY(GABON, 266),
        MAKE_COUNTRY(GEORGIA, 268),
        MAKE_COUNTRY(GAMBIA, 270),
        MAKE_COUNTRY(PALESTINE, 275),
        MAKE_COUNTRY(GERMANY, 276),
        MAKE_COUNTRY(GHANA, 288),
        MAKE_COUNTRY(GIBRALTAR, 292),
        MAKE_COUNTRY(KIRIBATI, 296),
        MAKE_COUNTRY(GREECE, 300),
        MAKE_COUNTRY(GREENLAND, 304),
        MAKE_COUNTRY(GRENADA, 308),
        MAKE_COUNTRY(GUADELOUPE, 312),
        MAKE_COUNTRY(GUAM, 316),
        MAKE_COUNTRY(GUATEMALA, 320),
        MAKE_COUNTRY(GUINEA, 324),
        MAKE_COUNTRY(GUYANA, 328),
        MAKE_COUNTRY(HAITI, 332),
        MAKE_COUNTRY(HOLY_SEE, 336),
        MAKE_COUNTRY(HONDURAS, 340),
        MAKE_COUNTRY(HONG_KONG, 344),
        MAKE_COUNTRY(HUNGARY, 348),
        MAKE_COUNTRY(ICELAND, 352),
        MAKE_COUNTRY(INDIA, 356),
        MAKE_COUNTRY(INDONESIA, 360),
        MAKE_COUNTRY(IRAN, 364),
        MAKE_COUNTRY(IRAQ, 368),
        MAKE_COUNTRY(IRELAND, 372),
        MAKE_COUNTRY(ISRAEL, 376),
        MAKE_COUNTRY(ITALY, 380),
        MAKE_COUNTRY(COTE_D_IVOIRE, 384),
        MAKE_COUNTRY(JAMAICA, 388),
        MAKE_COUNTRY(JAPAN, 392),
        MAKE_COUNTRY(KAZAKHSTAN, 398),
        MAKE_COUNTRY(JORDAN, 400),
        MAKE_COUNTRY(KENYA, 404),
        MAKE_COUNTRY(NORTH_KOREA, 408),
        MAKE_COUNTRY(SOUTH_KOREA, 410),
        MAKE_COUNTRY(KUWAIT, 414),
        MAKE_COUNTRY(KYRGYZSTAN, 417),
        MAKE_COUNTRY(LAO, 418),
        MAKE_COUNTRY(LEBANON, 422),
        MAKE_COUNTRY(LESOTHO, 426),
        MAKE_COUNTRY(LATVIA, 428),
        MAKE_COUNTRY(LIBERIA, 430),
        MAKE_COUNTRY(LIBYA, 434),
        MAKE_COUNTRY(LIECHTENSTEIN, 438),
        MAKE_COUNTRY(LITHUANIA, 440),
        MAKE_COUNTRY(LUXEMBOURG, 442),
        MAKE_COUNTRY(MACAO, 446),
        MAKE_COUNTRY(MADAGASCAR, 450),
        MAKE_COUNTRY(MALAWI, 454),
        MAKE_COUNTRY(MALAYSIA, 458),
        MAKE_COUNTRY(MALDIVES, 462),
        MAKE_COUNTRY(MALI, 466),
        MAKE_COUNTRY(MALTA, 470),
        MAKE_COUNTRY(MARTINIQUE, 474),
        MAKE_COUNTRY(MAURITANIA, 478),
        MAKE_COUNTRY(MAURITIUS, 480),
        MAKE_COUNTRY(MEXICO, 484),
        MAKE_COUNTRY(MONACO, 492),
        MAKE_COUNTRY(MONGOLIA, 496),
        MAKE_COUNTRY(MOLDOVA, 498),
        MAKE_COUNTRY(MONTENEGRO, 499),
        MAKE_COUNTRY(MONTSERRAT, 500),
        MAKE_COUNTRY(MOROCCO, 504),
        MAKE_COUNTRY(MOZAMBIQUE, 508),
        MAKE_COUNTRY(OMAN, 512),
        MAKE_COUNTRY(NAMIBIA, 516),
        MAKE_COUNTRY(NAURU, 520),
        MAKE_COUNTRY(NEPAL, 524),
        MAKE_COUNTRY(NETHERLANDS, 528),
        MAKE_COUNTRY(CURACAO, 531),
        MAKE_COUNTRY(ARUBA, 533),
        MAKE_COUNTRY(SINT_MAARTEN, 534),
        MAKE_COUNTRY(NEW_CALEDONIA, 540),
        MAKE_COUNTRY(VANUATU, 548),
        MAKE_COUNTRY(NEW_ZEALAND, 554),
        MAKE_COUNTRY(NICARAGUA, 558),
        MAKE_COUNTRY(NIGER, 562),
        MAKE_COUNTRY(NIGERIA, 566),
        MAKE_COUNTRY(NIUE, 570),
        MAKE_COUNTRY(NORFOLK_ISLAND, 574),
        MAKE_COUNTRY(NORWAY, 578),
        MAKE_COUNTRY(NORTHERN_MARIANA_ISLANDS, 580),
        MAKE_COUNTRY(MICRONESIA, 583),
        MAKE_COUNTRY(MARSHALL_ISLANDS, 584),
        MAKE_COUNTRY(PALAU, 585),
        MAKE_COUNTRY(PAKISTAN, 586),
        MAKE_COUNTRY(PANAMA, 591),
        MAKE_COUNTRY(PAPUA_NEW_GUINEA, 598),
        MAKE_COUNTRY(PARAGUAY, 600),
        MAKE_COUNTRY(PERU, 604),
        MAKE_COUNTRY(PHILIPPINES, 608),
        MAKE_COUNTRY(PITCAIRN, 612),
        MAKE_COUNTRY(POLAND, 616),
        MAKE_COUNTRY(PORTUGAL, 620),
        MAKE_COUNTRY(GUINEA_BISSAU, 624),
        MAKE_COUNTRY(TIMOR_LESTE, 626),
        MAKE_COUNTRY(PUERTO_RICO, 630),
        MAKE_COUNTRY(QATAR, 634),
        MAKE_COUNTRY(REUNION, 638),
        MAKE_COUNTRY(ROMANIA, 642),
        MAKE_COUNTRY(RUSSIAN_FEDERATION, 643),
        MAKE_COUNTRY(RWANDA, 646),
        MAKE_COUNTRY(SAINT_KITTS_AND_NEVIS, 659),
        MAKE_COUNTRY(ANGUILLA, 660),
        MAKE_COUNTRY(SAINT_LUCIA, 662),
        MAKE_COUNTRY(SAINT_VINCENT_AND_THE_GRENADINES, 670),
        MAKE_COUNTRY(SAN_MARINO, 674),
        MAKE_COUNTRY(SAO_TOME_AND_PRINCIPE, 678),
        MAKE_COUNTRY(SAUDI_ARABIA, 682),
        MAKE_COUNTRY(SENEGAL, 686),
        MAKE_COUNTRY(SERBIA, 688),
        MAKE_COUNTRY(SEYCHELLES, 690),
        MAKE_COUNTRY(SIERRA_LEONE, 694),
        MAKE_COUNTRY(SINGAPORE, 702),
        MAKE_COUNTRY(SLOVAKIA, 703),
        MAKE_COUNTRY(VIET_NAM, 704),
        MAKE_COUNTRY(SLOVENIA, 705),
        MAKE_COUNTRY(SOMALIA, 706),
        MAKE_COUNTRY(SOUTH_AFRICA, 710),
        MAKE_COUNTRY(ZIMBABWE, 716),
        MAKE_COUNTRY(SPAIN, 724),
        MAKE_COUNTRY(SOUTH_SUDAN, 728),
        MAKE_COUNTRY(SUDAN, 729),
        MAKE_COUNTRY(WESTERN_SAHARA, 732),
        MAKE_COUNTRY(SURINAME, 740),
        MAKE_COUNTRY(SWAZILAND, 748),
        MAKE_COUNTRY(SWEDEN, 752),
        MAKE_COUNTRY(SWITZERLAND, 756),
        MAKE_COUNTRY(SYRIAN_ARAB_REPUBLIC, 760),
        MAKE_COUNTRY(TAJIKISTAN, 762),
        MAKE_COUNTRY(THAILAND, 764),
        MAKE_COUNTRY(TOGO, 768),
        MAKE_COUNTRY(TOKELAU, 772),
        MAKE_COUNTRY(TONGA, 776),
        MAKE_COUNTRY(TRINIDAD_AND_TOBAGO, 780),
        MAKE_COUNTRY(UNITED_ARAB_EMIRATES, 784),
        MAKE_COUNTRY(TUNISIA, 788),
        MAKE_COUNTRY(TURKEY, 792),
        MAKE_COUNTRY(TURKMENISTAN, 795),
        MAKE_COUNTRY(TURKS_AND_CAICOS_ISLANDS, 796),
        MAKE_COUNTRY(TUVALU, 798),
        MAKE_COUNTRY(UGANDA, 800),
        MAKE_COUNTRY(UKRAINE, 804),
        MAKE_COUNTRY(MACEDONIA, 807),
        MAKE_COUNTRY(EGYPT, 818),
        MAKE_COUNTRY(UNITED_KINGDOM, 826),
        MAKE_COUNTRY(GUERNSEY, 831),
        MAKE_COUNTRY(JERSEY, 832),
        MAKE_COUNTRY(ISLE_OF_MAN, 833),
        MAKE_COUNTRY(TANZANIA, 834),
        MAKE_COUNTRY(UNITED_STATES_OF_AMERICA, 840),
        MAKE_COUNTRY(US_VIRGIN_ISLANDS, 850),
        MAKE_COUNTRY(BURKINA_FASO, 854),
        MAKE_COUNTRY(URUGUAY, 858),
        MAKE_COUNTRY(UZBEKISTAN, 860),
        MAKE_COUNTRY(VENEZUELA, 862),
        MAKE_COUNTRY(WALLIS_AND_FUTUNA, 876),
        MAKE_COUNTRY(SAMOA, 882),
        MAKE_COUNTRY(YEMEN, 887),
        MAKE_COUNTRY(ZAMBIA, 894),

        MAKE_SUBDIVISION(QUEBEC, CANADA, 'Q', 'C', 0),

        MAKE_SUBDIVISION(FLANDERS, BELGIUM, 'V', 'L', 'G'),
        MAKE_SUBDIVISION(WALLONIA, BELGIUM, 'W', 'A', 'L'),

        MAKE_SUBDIVISION(MIDI_PYRENEES, FRANCE, 'N', 0, 0),
        MAKE_SUBDIVISION(BRITTANY, FRANCE, 'E', 0, 0),

        MAKE_SUBDIVISION(BASQUE_COUNTRY, SPAIN, 'P', 'V', 0),
        MAKE_SUBDIVISION(CATALONIA, SPAIN, 'C', 'T', 0),
        MAKE_SUBDIVISION(GALICIA, SPAIN, 'G', 'A', 0),

        MAKE_SUBDIVISION(SCOTLAND, UNITED_KINGDOM, 'S', 'C', 'T'),
        MAKE_SUBDIVISION(WALES, UNITED_KINGDOM, 'W', 'L', 'S'),

        MAKE_LANGUAGE(ESPERANTO, 'e', 'p', 'o'),
        MAKE_LANGUAGE(IDO, 'i', 'd', 'o'),
        MAKE_LANGUAGE(INTERLINGUA, 'i', 'n', 'a'),
};

#undef MAKE_COUNTRY
#undef MAKE_SUBDIVISION
#undef MAKE_LANGUAGE
#undef LETTER_VALUE
#undef THREE_LETTER_CODE

#endif /* FV_FLAG_H */
